services:
  jellyseerr-ts:
    image: tailscale/tailscale:latest
    hostname: jellyseerr
    environment:
      - TS_AUTHKEY=tskey-auth- #Update Key from portal#
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/jellyseerr.json
      - TS_USERSPACE=true
    volumes:
      - /mnt/ssd1/appdata/jellyseerr/ts-config:/config
      - /mnt/ssd1/appdata/jellyseerr/ts-state:/var/lib/tailscale
    restart: unless-stopped
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/India/Kolkata
      - PORT=5055 #optional
    #ports:
      #- 5055:5055
    volumes:
      - /path/to/appdata/config:/app/config
    network_mode: service:jellyseerr-ts
    restart: unless-stopped

volumes:
  model-cache: